[num,text,raw]=xlsread('tt06s_new.xlsx');
tt06s=num;
[num,text,raw]=xlsread('tt06x_new.xlsx');
tt06x=num;
[num,text,raw]=xlsread('tt07s_new.xlsx');
tt07s=num;
[num,text,raw]=xlsread('tt07x_new.xlsx');
tt07x=num;
[num,text,raw]=xlsread('tt08s_new.xlsx');
tt08s=num;
[num,text,raw]=xlsread('tt08x_new.xlsx');
tt08x=num;
[num,text,raw]=xlsread('tt09s_new.xlsx');
tt09s=num;
[num,text,raw]=xlsread('tt09x_new.xlsx');
tt09x=num;
[num,text,raw]=xlsread('tt10s_new.xlsx');
tt10s=num;
[num,text,raw]=xlsread('tt10x_new.xlsx');
tt10x=num;
%绘图
%6
figure;
subplot(1,2,1);
plot(tt06s(:,1),tt06s(:,2),'b');
hold on;
plot(tt06s(:,1),tt06s(:,3),'r');
xlabel('时间');
ylabel('发车间隔/min');
title('嘉定104路 9月6日 上行方向 发车间隔分析');
legend('计划发车间隔','发车间隔');
datetick('x',13);
subplot(1,2,2);
plot(tt06x(:,1),tt06x(:,2),'b');
hold on;
plot(tt06x(:,1),tt06x(:,3),'r');
xlabel('时间');
ylabel('与时刻表偏差/min');
title('嘉定104路 9月6日 下行方向 发车间隔分析');
legend('计划发车间隔','发车间隔');
datetick('x',13);

%7
figure;
subplot(1,2,1);
plot(tt07s(:,1),tt07s(:,2),'b');
hold on;
plot(tt07s(:,1),tt07s(:,3),'r');
xlabel('时间');
ylabel('发车间隔/min');
title('嘉定104路 9月7日 上行方向 发车间隔分析');
legend('计划发车间隔','发车间隔');
datetick('x',13);
subplot(1,2,2);
plot(tt07x(:,1),tt07x(:,2),'b');
hold on;
plot(tt07x(:,1),tt07x(:,3),'r');
xlabel('时间');
ylabel('与时刻表偏差/min');
title('嘉定104路 9月7日 下行方向 发车间隔分析');
legend('计划发车间隔','发车间隔');
datetick('x',13);

%8
figure;
subplot(1,2,1);
plot(tt08s(:,1),tt08s(:,2),'b');
hold on;
plot(tt08s(:,1),tt08s(:,3),'r');
xlabel('时间');
ylabel('发车间隔/min');
title('嘉定104路 9月8日 上行方向 发车间隔分析');
legend('计划发车间隔','发车间隔');
datetick('x',13);
subplot(1,2,2);
plot(tt08x(:,1),tt08x(:,2),'b');
hold on;
plot(tt08x(:,1),tt08x(:,3),'r');
xlabel('时间');
ylabel('与时刻表偏差/min');
title('嘉定104路 9月8日 下行方向 发车间隔分析');
legend('计划发车间隔','发车间隔');
datetick('x',13);

%9
figure;
subplot(1,2,1);
plot(tt09s(:,1),tt09s(:,2),'b');
hold on;
plot(tt09s(:,1),tt09s(:,3),'r');
xlabel('时间');
ylabel('发车间隔/min');
title('嘉定104路 9月9日 上行方向 发车间隔分析');
legend('计划发车间隔','发车间隔');
datetick('x',13);
subplot(1,2,2);
plot(tt09x(:,1),tt09x(:,2),'b');
hold on;
plot(tt09x(:,1),tt09x(:,3),'r');
xlabel('时间');
ylabel('与时刻表偏差/min');
title('嘉定104路 9月9日 下行方向 发车间隔分析');
legend('计划发车间隔','发车间隔');
datetick('x',13);

%10
figure;
subplot(1,2,1);
plot(tt10s(:,1),tt10s(:,2),'b');
hold on;
plot(tt10s(:,1),tt10s(:,3),'r');
xlabel('时间');
ylabel('发车间隔/min');
title('嘉定104路 9月10日 上行方向 发车间隔分析');
legend('计划发车间隔','发车间隔');
datetick('x',13);
subplot(1,2,2);
plot(tt10x(:,1),tt10x(:,2),'b');
hold on;
plot(tt10x(:,1),tt10x(:,3),'r');
xlabel('时间');
ylabel('与时刻表偏差/min');
title('嘉定104路 9月10日 下行方向 发车间隔分析');
legend('计划发车间隔','发车间隔');
datetick('x',13);